# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint & Test

on:
  pull_request:
    branches: "*"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: ${{ env.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache_node_modules
        with:
          # check diff of package.json and yarn.lock
          key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}
          path: "**/node_modules"

      - name: Install Dependencies
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
        env:
          PROVIDER_URL: https://goerli.infura.io/v3/${{ secrets.INFURA_KEY }}
