name: Lint & Test

on:
  pull_request:
    branches: ["*"]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache_node_modules
        with:
          # check diff of package.json and yarn.lock
          key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          path: "**/node_modules"

      - name: Install dependencies
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npm run build:all

      - name: Lint
<<<<<<< HEAD
        run: yarn workspace evm lint # TODO: yarn workspaces run lintへ変更

      - name: Test
        run: yarn workspace evm test # TODO: yarn workspaces run testへ変更
=======
        run: npm run lint:all

      - name: Test
        run: npm run test:evm
>>>>>>> 32096d3351550abf7ef1da5d64ef5f552f61f06b
        env:
          PROVIDER_URL: https://goerli.infura.io/v3/${{ secrets.INFURA_KEY }}
