name: Publish npm package

on:
  push:
    tags:
      - "v*"

env:
  # Check available versions below
  # https://github.com/actions/node-versions/blob/main/versions-manifest.json
  node-version: "16.x"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: ${{ env.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache_node_modules
        with:
          # check diff of package.json and yarn.lock
          key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}
          path: "**/node_modules"

      - name: Authenticate with GitHub PAT
        run: echo "npmAuthToken:" ${{ secrets.NPM_TOKEN }} >> ~/.yarnrc.yml

      - name: Install Dependencies
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Publish private npm package
        run: yarn npm publish
